[package]
name = "sputnik"
version = "0.1.0"
edition = "2021"

[dependencies]
tokenizer = { path = "../tokenizer"}
render_tree = { path = "../render_tree"}
parser = { path = "../parser"}
dom = { path = "../dom"}
typed-arena = "2.0.2"
