[package]
name = "sputnik"
version.workspace = true
edition.workspace = true

[dependencies]
html_tokenizer = { path = "../html_tokenizer"}
layout = { path = "../layout"}
html_parser = { path = "../html_parser"}
dom = { path = "../dom"}
typed-arena = "2.0.2"
