[package]
name = "sputnik"
version.workspace = true
edition.workspace = true

[dependencies]
tokenizer = { path = "../tokenizer"}
render_tree = { path = "../render_tree"}
layout = { path = "../layout"}
html_parser = { path = "../html_parser"}
dom = { path = "../dom"}
typed-arena = "2.0.2"
