[package]
name = "html_parser"
version.workspace = true
edition.workspace = true

[dependencies]
html_tokenizer = { path = "../html_tokenizer" }
dom = { path = "../dom" }
html = { path = "../html" }
typed-arena = "2.0.2"
